version: '3.8'

services:
  authentication:
    image: authentication-service
    build:
      context: .
      dockerfile: ./src/Services/Authentication/Dockerfile
    ports:
      - "8080:80"

  evaluation:
    image: evaluation-service
    build:
      context: .
      dockerfile: ./src/Services/Evaluation/Dockerfile
    ports:
      - "8081:80"
